### ISSUE TITLE
Fix issues where description isn't found

### ISSUE THREAD

**Issue by ZakMiller** [SylvanSign/Blue-Harvest#17]
Causes

- [x] Redirecting to mobile which doesn't have meta description (vk.com)
- [ ] redirects that assume you have a cookie (blogspot.com)
- [ ] Site is unreachable (e.g. microsoftonline.com, ytimg.com)
  - Maybe we just leave this as the last issue to solve, and worst case just filter these out?
- [ ] certain sites have a `META NAME="Description"` or some weird casing of the tag. Example (view-source:http://www.monografias.com/)
  - Floki doesn't support case insensitive selectors, so maybe we just lowercase the whole string first?

**Comment by SylvanSign** [comment]
Decided to go with a fallback to `title` tag when we can't find the meta description. Good enough for now
